apiVersion: v1
kind: Service
metadata:
  name: redis-db  # <--- CAMBIO AQUÍ (Antes era 'redis')
spec:
  ports:
  - port: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      automountServiceAccountToken: false
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
            ephemeral-storage: "100Mi"
          limits:
            memory: "128Mi"  # <--- Esto es lo que pide SonarQube
            cpu: "100m"
            ephemeral-storage: "200Mi"